# Generated by Django 3.1.5 on 2021-01-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylotto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guessnumbers',
            name='update_date',
            field=models.DateTimeField(null=True),
        ),
    ]
