# Generated by Django 3.1.5 on 2021-01-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylotto', '0002_auto_20210123_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guessnumbers',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
